travis:
  secure:
    BINSTAR_TOKEN: mUn5Cn5VjIJPrTHY9Ln921A07opNMF0JpjoRClLwaeTylp/5FowXEM22DLLEtik8oPDBJdOFCo4vapSIlZWHctzVASn64tbvgQY0KTWVRfgkckPEDsEc/JRGVZpopDmTAgm2JzMa3/8gVksgBEgNqc/+UFZLny3iasV0gwwCsvjdCdifkYqwEpPwiCew2ltHDkfd1aEjNHbEzikvg06/neIh+W7UYnyzBbnhRcUyBM3adtrw5b6rcOczEbozy47xjshFRg0GE4YPP/rxppiEusj83g1/SFDYMArTKxboF2Ptaz88t13IbVsdwovBi+7OazTydBHwhjHqNh+AoPM7dWCEwb9yM3dc87ykArCOyqXEAN7sGhgJhLjWfv3HCTA9hH/zmwOeCK1lxxeF5ouoae6HhftU8Re5/2b7AdbY6L4sMc5A9gaawml7+GDHG3Fnr4dbbXAiIYur0O6st1VzfuWPT+Jgjn6m5AD42gbl2J6M0QZBUKPc+nUHmC87HGCtqUEaJLwr+owb2Y7QbfewpnzYuzjS2mY+l8u2od/h3qiowN0Qq3Z7P7+FyqgjZkxB8VxuW7Np8g75aYohSpv1MT8cvGGmOy5MOTyAH/Yl3XeLQuHyJ7GC560QTscXda+MGTEcTm+D6qeNgP710DIx4kLieEG/7LXYt2qdRGTxRvg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
